---
title: "New NTEE Codes (NTEEV2)"
format: 
  html:
    grid: 
      body-width: 2000px
editor: visual
---

```{r, include=FALSE}
library(readr)
library(dplyr)
library(DT)

ntee_df <- readr::read_csv("https://raw.githubusercontent.com/Nonprofit-Open-Data-Collective/mission-taxonomies/main/NTEEV2/ntee-crosswalk.csv")

cols <- c("Original NTEE",
          "NTEEV2",
          "Level 1",
          "Level 2",
          "Level 3",
          "Level 3 Description",
          "Level 4",
          "Level 4 Description",
          "Level 5")

fctr <- c("Level 1",
          "Level 2",
          "Level 3",
          "Level 4",
          "Level 5")

ntee_table <- ntee_df %>%
  dplyr::mutate(level1 = paste(level1,
                               level1.label,
                               sep = " - "),
                level2 = paste(substr(level2, 1, 3),
                               level2.label,
                               sep = " - "),
                level5 = paste(level5,
                               level5.label,
                               sep = " - ")) %>% 
  dplyr::rename("Original NTEE" = NTEE,
                "NTEEV2" = NTEE2,
                "Level 1" = level1,
                "Level 2" = level2,
                "Level 3" = level3,
                "Level 3 Description" = level3.label,
                "Level 4" = level4,
                "Level 4 Description" = level4.label,
                "Level 5" = level5) %>% 
  dplyr::select(all_of(cols)) %>% 
  dplyr::mutate(across(all_of(fctr), ~ as.factor(.x)))
```

```{r echo=FALSE}

datatable(ntee_table, 
          filter = 'top', 
          options = list(pageLength = 10, 
                         autoWidth = TRUE,
                         columnDefs = list(list(
                           width = "150px",
                           targets = c(3, 4, 9)
                         ),
                         list(width = "200px",
                              targets = c(6)),
                         list(width = "60px",
                              targets = c(5, 7)),
                         list(width = "90px",
                              targets = c(2)))
))

```
