---
title: "NCCS BMF Data Catalog"
format: html
editor: visual
execute: 
  echo: false
  warning: false
---

```{r}
#| echo: false

library( dplyr )
library( knitr )
library( kableExtra )
library( stringr )
library( pander )

aws_df <- read.csv(
  "AWS-NCCSDATA.csv"
)
source("build-catalog-functions.R")
nccs_legacy_base_url <- "https://urbaninstitute.github.io/nccs-legacy/dictionary/core/core_archive_html/"
aws_base_url <- "https://nccsdata.s3.amazonaws.com/"

state_mapping <- c(
  "AK" = "Alaska",
  "AL" = "Alabama",
  "AR" = "Arkansas",
  "AS" = "American Samoa",
  "AZ" = "Arizona",
  "CA" = "California",
  "CO" = "Colorado",
  "CT" = "Connecticut",
  "DC" = "District of Columbia",
  "DE" = "Delaware",
  "FL" = "Florida",
  "GA" = "Georgia",
  "GU" = "Guam",
  "HI" = "Hawaii",
  "IA" = "Iowa",
  "ID" = "Idaho",
  "IL" = "Illinois",
  "IN" = "Indiana",
  "KS" = "Kansas",
  "KY" = "Kentucky",
  "LA" = "Louisiana",
  "MA" = "Massachusetts",
  "MD" = "Maryland",
  "ME" = "Maine",
  "MI" = "Michigan",
  "MN" = "Minnesota",
  "MO" = "Missouri",
  "MP" = "Northern Mariana Islands",
  "MS" = "Mississippi",
  "MT" = "Montana",
  "NC" = "North Carolina",
  "ND" = "North Dakota",
  "NE" = "Nebraska",
  "NH" = "New Hampshire",
  "NJ" = "New Jersey",
  "NM" = "New Mexico",
  "NV" = "Nevada",
  "NY" = "New York",
  "OH" = "Ohio",
  "OK" = "Oklahoma",
  "OR" = "Oregon",
  "PA" = "Pennsylvania",
  "PR" = "Puerto Rico",
  "RI" = "Rhode Island",
  "SC" = "South Carolina",
  "SD" = "South Dakota",
  "TN" = "Tennessee",
  "TX" = "Texas",
  "UT" = "Utah",
  "Un" = "Unmapped",
  "VA" = "Virginia",
  "VI" = "U.S. Virgin Islands",
  "VT" = "Vermont",
  "WA" = "Washington",
  "WI" = "Wisconsin",
  "WV" = "West Virginia",
  "WY" = "Wyoming"
)
```

<br>

<hr>

<br>

**Overview**

Files are organized by **state/territory**. Unmapped records are saved in the "Unmapped" File. A link to the data dictionary is available here:

<a href="https://nccsdata.s3.amazonaws.com/harmonized/harmonized_data_dictionary.xlsx" class="button3">Download Data Dictionary</a>

<br>

<hr>

<br>

#### Unified BMF by State/Territory

```{r}
paths <- aws_df$Key[grepl("harmonized/bmf/unified", aws_df$Key)]
paths <- paths[grepl("_BMF_", paths)]

state_abbrs <- substr(paths, 24, 25)

download_urls <- paste0(aws_base_url, paths)


download_buttons <- make_buttons(urls = download_urls, button_name = "download")
size <- aws_df %>%
  dplyr::filter(Key %in% paths) %>%
  dplyr::mutate(size_mb = paste0(as.character(round(Size / 1000000, 1)), " mb")) %>%
  dplyr::pull("size_mb")

state <- unlist(state_mapping)
catalog <- data.frame(download_buttons, size, state)

rownames(catalog) <- NULL
catalog %>%
  knitr::kable(
    escape = FALSE,
    col.names = c("Download Link", "Size", "State/Territory"),
    format = "html"
  ) %>%
  kableExtra::kable_styling()
```

## Legacy BMF

```{r}

bmf_legacy_catalog <- construct_catalog(s3_catalog = aws_df,
                             series = "bmf",
                             paths = aws_df$Key)
bmf_legacy_catalog |>
  knitr::kable(escape=FALSE,
               col.names = c(
                 "Download Link",
                 "Data Dictionary",
                 "Size",
                 "Month",
                 "Year"
               ),
               format = "html") |>
   kableExtra::kable_styling()
```

<br>

<hr>

<br>

```{=html}
<style>


h1.title {
 font-size: 60px;
 color: #0a4c6a;
}


h4, .h4 {
    font-size: 40px;
    color: #1696d2;
    margin-bottom: 50px;
}



.button {
  background-color: white;
  color:  #12719e;
  border: 2px solid  #12719e;   /* #008CBA; */
  padding: 5px 10px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 14px;
  border-radius: 12px;
  width: 150px;
}
 
.button {
  transition-duration: 0.4s;
}

.button:hover {
  background-color: #1696d2; 
  color: white;
  border: 2px solid #12719e;
}


.button2 {
  background-color: white;
  color: #12719e;
  border: 2px solid #9d9d9d;   /* #008CBA; */
  padding: 5px 10px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 14px;
  border-radius: 12px;
  width: 150px;
}

.button2 {
  transition-duration: 0.4s;
}

.button2:hover {
  background-color: #fff2cf; 
  color: #1696d2;
  font-weight: bold;
  border: 2px solid #1696d2;
}


.center {text-align: center;}

table td {
  vertical-align: middle;
}

blockquote {
    border-left: 4px solid #1696d2;
    margin-left: 10px;
    margin-inline-start: 0px;
    margin-inline-end: 0px;
    padding: 15px;
}

.button3 {
  background-color: #0a4c6a;
  color: white;
  border: 2px solid #0a4c6a;   
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 20px;
  border-radius: 4px;
  width: 200px;
  display: grid;
  margin: auto;
}
</style>
```
