---
title: "NCCS Revocations Data Catalog"
# Format and execute settings inherited from _quarto.yml
---

```{r}
#| echo: false

library( dplyr )
library( knitr )
library( kableExtra )
library( stringr )
library( flextable )
library( pander )

source("build-catalog-functions.R")

fn  <- "AWS-NCCSDATA.csv"
d   <- read.csv( fn )

# fn   <- "AWS-NCCSDATA.csv"
# path <- "https://raw.githubusercontent.com/UrbanInstitute/nccs/main/catalogs/"
# d    <- read.csv( paste0( path, fn  ) )

```

<br>
<hr>
<br>


#### Import to R 

Retrieve the most recent file available using the following script: 

```{r, eval=F, echo=T}
part_1 <- "https://nccsdata.s3.us-east-1.amazonaws.com/raw/revocations/" 
YYYYMM <- format( Sys.Date(), "%Y-%m" )
part_2 <- "-REVOCATIONS-ORGS.csv"

URL <- paste0( part_1, YYYYMM, part_2 )
d <- read.csv( URL )
```


<br>
<hr>
<br>

#### Download Data in CSV Format 

```{r}
catalog <- get_catalog_revocations( d$URL )

catalog %>%
  knitr::kable( format="html", escape=FALSE ) %>%
  kableExtra::kable_styling() 
```

<br>

<hr>

<br>

<!-- Styles loaded from shared catalog.css via _quarto.yml -->
